#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/Aria2-Pro-Docker https://github.com/DDS-Derek/Aria2-Pro-Docker
#
# Copyright (c) 2020-2022 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: Nightly & Tacker Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build Aria2-Pro-Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
            linux/arm/v6
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/aria2-pro:nightly

      - 
        name: Smartdns GFWList
        run: |
          echo > /tmp/blank

          curl -sSL https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt > /tmp/all
          curl -sSL https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_all.txt > /tmp/AT_all
          curl -sSL https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt > /tmp/trackerslist_all
          cat /tmp/all /tmp/blank /tmp/AT_all /tmp/blank /tmp/trackerslist_all | uniq | sed ":a;N;s/\n/,/g;ta" | sed -e "s/,,/,/g" -e "s/,$//g" | tr -d "\n" > all.list
          cat /tmp/all /tmp/blank /tmp/AT_all /tmp/blank /tmp/trackerslist_all | uniq | sed ":a;N;s/\n/,/g;ta" | sed -e "s/,,/,/g" -e "s/,$//g" | sed -e "s/,/\n/g" > all_raw.list

          curl -sSL https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/best.txt > /tmp/best
          curl -sSL https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_best.txt > /tmp/AT_best
          curl -sSL https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt > /tmp/trackerslist_best
          cat /tmp/best /tmp/blank /tmp/AT_best /tmp/blank /tmp/trackerslist_best | uniq | sed ":a;N;s/\n/,/g;ta" | sed -e "s/,,/,/g" -e "s/,$//g" | tr -d "\n" > best.list
          cat /tmp/best /tmp/blank /tmp/AT_best /tmp/blank /tmp/trackerslist_best | uniq | sed ":a;N;s/\n/,/g;ta" | sed -e "s/,,/,/g" -e "s/,$//g" | sed -e "s/,/\n/g" > best_raw.list

      - 
        name: Push List
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: tracker
          commit_message: Update Trackers
          skip_dirty_check: false
          commit_user_name: Action Bot
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Action <actions@github.com>