#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/Aria2-Pro-Docker https://github.com/DDS-Derek/Aria2-Pro-Docker
#
# Copyright (c) 2020-2022 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: Build

on:
    release:
        types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build Aria2-Pro-Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
            linux/arm/v6
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/aria2-pro:${{ steps.set-version.outputs.version }}
             ${{ secrets.DOCKER_USERNAME }}/aria2-pro:latest
             
      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ddsderek/aria2-pro
          short-description: Adapted from P3TERX/Aria2-Pro Image
          readme-filepath: ./README.md
